<?php

/**
 * inc/log_login.php
 *
 * Login/logout event recorder for imis_history_login_logs.
 * Called via AJAX POST from the front-end when a session opens or closes.
 *
 * Timezone notes
 * ──────────────
 * [TZ-1] date_default_timezone_set('Asia/Manila') is called early so every
 *        date() / strtotime() call in this file uses UTC+8 automatically.
 *
 * [TZ-2] $conn->exec("SET time_zone = '+08:00'") aligns the MySQL session
 *        timezone with PHP.  This is a defensive net — correctness does NOT
 *        rely on it because $currentTime is generated by PHP's date(), not
 *        MySQL's NOW().  See [TZ-3] below.
 *
 * [TZ-3] All timestamps are generated in PHP via date('Y-m-d H:i:s') and
 *        bound as parameters.  MySQL's NOW() is intentionally avoided so the
 *        timezone is always governed by the PHP setting, not the DB server
 *        default.
 *
 * Other fixes
 * ───────────
 * [FIX-1] Removed non-existent `logout_reason` column from UPDATE.
 * [FIX-2] Added `status` update on logout ('logged_out' / 'timeout').
 * [FIX-3] require_once uses __DIR__-relative path (CWD-independent).
 * [FIX-4] FILTER_SANITIZE_STRING replaced with trim() + htmlspecialchars().
 * [FIX-5] Proxy-aware IP resolution on both login and logout paths.
 * [FIX-6] INSERT explicitly sets status = 'active'.
 * [FIX-7] PDO ERRMODE_EXCEPTION enforced so failures surface immediately.
 */

declare(strict_types=1);

// ── Timezone ──────────────────────────────────────────────────────────────────
// [TZ-1] Must be set BEFORE any date() call.
date_default_timezone_set('Asia/Manila');

// ── Session ───────────────────────────────────────────────────────────────────
if (session_status() === PHP_SESSION_NONE) {
    session_start();
}

// ── Dependencies ──────────────────────────────────────────────────────────────
// [FIX-3] __DIR__ makes this work regardless of the web-server's CWD.
require_once __DIR__ . '/../includes/connect.php';

// ── Response headers ─────────────────────────────────────────────────────────
header('Content-Type: application/json');
header('Cache-Control: no-store, no-cache, must-revalidate, max-age=0');

// ─────────────────────────────────────────────────────────────────────────────
// HELPERS
// ─────────────────────────────────────────────────────────────────────────────

/**
 * [FIX-5] Resolve the real client IP, walking proxy headers in priority order.
 * Private/reserved IPs are accepted so intranet clients are logged correctly.
 */
function resolveClientIp(): string
{
    $candidates = [
        'HTTP_CLIENT_IP',
        'HTTP_X_FORWARDED_FOR',
        'HTTP_X_FORWARDED',
        'HTTP_FORWARDED_FOR',
        'HTTP_FORWARDED',
        'REMOTE_ADDR',
    ];

    foreach ($candidates as $key) {
        $value = $_SERVER[$key] ?? '';
        if ($value === '') {
            continue;
        }

        // X-Forwarded-For can be "client, proxy1, proxy2" — take the first.
        $ip = trim(explode(',', $value)[0]);

        if (filter_var($ip, FILTER_VALIDATE_IP)) {
            return $ip;
        }
    }

    return '0.0.0.0';
}

/**
 * [FIX-4] Safe username sanitiser — no deprecated FILTER_SANITIZE_STRING.
 */
function sanitiseUsername(string $raw): string
{
    return htmlspecialchars(trim($raw), ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8');
}

/**
 * Emit a JSON error response and terminate.
 */
function jsonError(int $httpCode, string $message): never
{
    http_response_code($httpCode);
    echo json_encode(['success' => false, 'message' => $message]);
    exit();
}

// ─────────────────────────────────────────────────────────────────────────────
// VALIDATION
// ─────────────────────────────────────────────────────────────────────────────

if ($_SERVER['REQUEST_METHOD'] !== 'POST') {
    jsonError(405, 'Method not allowed');
}

$action   = $_POST['action'] ?? '';
$userId   = filter_input(INPUT_POST, 'user_id', FILTER_VALIDATE_INT);
$username = sanitiseUsername($_POST['username'] ?? '');  // [FIX-4]

if (!$action || !$userId || $username === '') {
    error_log('[log_login] Missing/invalid parameters'
        . ' action='    . var_export($action,   true)
        . ' user_id='   . var_export($userId,   true)
        . ' username='  . var_export($username, true));
    jsonError(400, 'Missing or invalid parameters');
}

// ── Database connection guard ─────────────────────────────────────────────────
if (!isset($conn) || !($conn instanceof PDO)) {
    error_log('[log_login] $conn is not a PDO instance — check connect.php');
    jsonError(500, 'Database unavailable');
}

// [FIX-7] Enforce exception mode so failed queries are never swallowed silently.
$conn->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);

// [TZ-2] Align MySQL session timezone with PHP as a defensive net.
$conn->exec("SET time_zone = '+08:00'");

// ─────────────────────────────────────────────────────────────────────────────
// ACTION DISPATCH
// ─────────────────────────────────────────────────────────────────────────────

try {

    // [TZ-3] PHP generates the timestamp — timezone is 100% controlled by
    //        date_default_timezone_set('Asia/Manila') above.
    $currentTime = date('Y-m-d H:i:s');
    $sessionId   = session_id();
    $ipAddress   = resolveClientIp();
    $userAgent   = substr($_SERVER['HTTP_USER_AGENT'] ?? 'Unknown', 0, 255);

    switch ($action) {

        // ── LOGIN ─────────────────────────────────────────────────────────────
        case 'login':

            // Concurrent-login guard: close any other active sessions for this
            // user that belong to a DIFFERENT session ID.
            $stmtClose = $conn->prepare(
                "UPDATE imis_history_login_logs
                    SET logout_time  = :now,
                        status       = 'logged_out',
                        updated_at   = CURRENT_TIMESTAMP
                  WHERE user_id      = :uid
                    AND status       = 'active'
                    AND session_id  != :sid"
            );
            $stmtClose->execute([
                ':now' => $currentTime,
                ':uid' => $userId,
                ':sid' => $sessionId,
            ]);

            if ($stmtClose->rowCount() > 0) {
                error_log("[log_login] Closed {$stmtClose->rowCount()} stale session(s) for user_id={$userId}");
            }

            // [FIX-6] status is explicit in the INSERT.
            $stmtInsert = $conn->prepare(
                "INSERT INTO imis_history_login_logs
                     (user_id, username, login_time, ip_address, user_agent, session_id, status)
                 VALUES
                     (:uid, :uname, :now, :ip, :ua, :sid, 'active')"
            );

            $stmtInsert->execute([
                ':uid'   => $userId,
                ':uname' => $username,
                ':now'   => $currentTime,      // [TZ-3] PHP timestamp
                ':ip'    => $ipAddress,
                ':ua'    => $userAgent,
                ':sid'   => $sessionId,
            ]);

            $logId = (int) $conn->lastInsertId();

            if ($logId === 0) {
                error_log('[log_login] INSERT succeeded but lastInsertId() returned 0');
                jsonError(500, 'Log insert did not return an ID');
            }

            // Store for fast PK lookup on logout.
            $_SESSION['login_log_id'] = $logId;

            error_log("[log_login] Login recorded — log_id={$logId}, user={$username}, ip={$ipAddress}, time={$currentTime}");

            echo json_encode([
                'success' => true,
                'message' => 'Login logged',
                'log_id'  => $logId,
            ]);
            break;

        // ── LOGOUT ────────────────────────────────────────────────────────────
        case 'logout':

            $reason = $_POST['reason'] ?? 'manual';

            // [FIX-1+2] logout_reason column does not exist in the schema;
            //           the status enum is updated instead.
            $status = in_array($reason, ['timeout', 'idle'], true)
                ? 'timeout'
                : 'logged_out';

            $logId = isset($_SESSION['login_log_id'])
                ? (int) $_SESSION['login_log_id']
                : null;

            if ($logId !== null && $logId > 0) {
                // Fast path: update by primary key.
                $stmtLogout = $conn->prepare(
                    "UPDATE imis_history_login_logs
                        SET logout_time  = :now,
                            status       = :status,
                            updated_at   = CURRENT_TIMESTAMP
                      WHERE id           = :id
                        AND status       = 'active'"
                );
                $stmtLogout->execute([
                    ':now'    => $currentTime,   // [TZ-3] PHP timestamp
                    ':status' => $status,
                    ':id'     => $logId,
                ]);
                error_log("[log_login] Logout by log_id={$logId}, status={$status}, rows={$stmtLogout->rowCount()}, time={$currentTime}");
            } else {
                // Fallback: match by user_id + session_id.
                error_log("[log_login] Logout fallback — no login_log_id in session for user_id={$userId}");
                $stmtLogout = $conn->prepare(
                    "UPDATE imis_history_login_logs
                        SET logout_time  = :now,
                            status       = :status,
                            updated_at   = CURRENT_TIMESTAMP
                      WHERE user_id      = :uid
                        AND session_id   = :sid
                        AND status       = 'active'"
                );
                $stmtLogout->execute([
                    ':now'    => $currentTime,   // [TZ-3] PHP timestamp
                    ':status' => $status,
                    ':uid'    => $userId,
                    ':sid'    => $sessionId,
                ]);
                error_log("[log_login] Fallback — user_id={$userId}, rows={$stmtLogout->rowCount()}, time={$currentTime}");
            }

            $updated = $stmtLogout->rowCount();

            echo json_encode([
                'success' => true,
                'message' => $updated > 0
                    ? 'Logout logged'
                    : 'No active session found (already closed?)',
                'rows'    => $updated,
            ]);
            break;

        default:
            jsonError(400, 'Invalid action: ' . htmlspecialchars($action, ENT_QUOTES, 'UTF-8'));
    }
} catch (PDOException $e) {
    error_log('[log_login] PDOException: ' . $e->getMessage()
        . ' | SQLSTATE: ' . $e->getCode()
        . ' | action='   . $action
        . ' | user_id='  . $userId);
    jsonError(500, 'Database error — check server logs');
} catch (Throwable $e) {
    error_log('[log_login] Unexpected error: ' . $e->getMessage()
        . ' | ' . $e->getFile() . ':' . $e->getLine());
    jsonError(500, 'Unexpected server error');
} finally {
    $conn = null;
}

exit();
