<?php
// includes/SystemAccessLogger.php

/**
 * SystemAccessLogger
 * ──────────────────
 * Records every successful system/project access made through the IMIS
 * dashboard into imis_history_access_logs.
 *
 * Design notes
 * ────────────
 * - username, ip_address, user_agent, and session_id are NOT stored here —
 *   they already exist in imis_history_login_logs.  The login_log_id FK
 *   links to that row; JOIN on it to retrieve those details.
 * - Timestamps are always generated by PHP (date('Y-m-d H:i:s')), never by
 *   MySQL's NOW(), so correctness does not depend on the DB server timezone.
 * - A configurable cooldown window (default 5 minutes) prevents duplicate
 *   entries when a user opens the same system multiple times in quick
 *   succession, while still capturing genuine re-access events.
 * - All failures are logged to the PHP error log and return false — a logging
 *   failure never throws to the caller and never blocks a redirect.
 */
class SystemAccessLogger
{
    private PDO $conn;

    /**
     * Minimum gap (minutes) between two entries for the same user + project.
     * Set to 0 to disable deduplication entirely.
     */
    private int $cooldownMinutes;

    public function __construct(PDO $conn, int $cooldownMinutes = 5)
    {
        // Defensive net: timezone is already set by connect.php, but guard
        // against contexts where this class is instantiated without it.
        date_default_timezone_set('Asia/Manila');

        $this->conn            = $conn;
        $this->cooldownMinutes = max(0, $cooldownMinutes);

        try {
            $this->conn->exec("SET time_zone = '+08:00'");
            $this->conn->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
        } catch (PDOException $e) {
            error_log('SystemAccessLogger::__construct — ' . $e->getMessage());
        }
    }

    // ─────────────────────────────────────────────────────────────────────────
    // PUBLIC API
    // ─────────────────────────────────────────────────────────────────────────

    /**
     * Record a successful system access event.
     *
     * login_log_id is read from $_SESSION['login_log_id'] — set by
     * LoginLogger::logLogin() at login time — so no extra parameter is needed.
     *
     * @param  int    $userId      Authenticated user's primary key
     * @param  int    $projectId   imis_projects.id
     * @param  string $projectCode imis_projects.code_name  (e.g. 'OTRS')
     * @param  string $roleName    Role the user holds in this project
     * @return bool   true on insert or deliberate cooldown skip; false on error
     */
    public function logAccess(
        int    $userId,
        int    $projectId,
        string $projectCode,
        string $roleName
    ): bool {
        try {
            if ($this->cooldownMinutes > 0 && $this->isWithinCooldown($userId, $projectId)) {
                return true;  // Deliberate dedup skip — not an error
            }

            $now        = $this->now();
            $loginLogId = isset($_SESSION['login_log_id'])
                ? (int) $_SESSION['login_log_id']
                : null;

            $stmt = $this->conn->prepare(
                "INSERT INTO imis_history_access_logs
                     (login_log_id, user_id, project_id, project_code, role_name, accessed_at)
                 VALUES
                     (:login_log_id, :user_id, :project_id, :project_code, :role_name, :now)"
            );

            $stmt->execute([
                ':login_log_id' => $loginLogId,
                ':user_id'      => $userId,
                ':project_id'   => $projectId,
                ':project_code' => $projectCode,
                ':role_name'    => $roleName,
                ':now'          => $now,
            ]);

            error_log("SystemAccessLogger — logged: user_id={$userId} project={$projectCode} role={$roleName} login_log_id=" . ($loginLogId ?? 'NULL') . " time={$now}");
            return true;
        } catch (PDOException $e) {
            error_log('SystemAccessLogger::logAccess — PDOException: ' . $e->getMessage()
                . " | user_id={$userId} project_id={$projectId}");
            return false;
        } catch (Throwable $e) {
            error_log('SystemAccessLogger::logAccess — Unexpected: ' . $e->getMessage());
            return false;
        }
    }

    /**
     * Retrieve the access history for a specific user (newest first).
     * JOINs imis_history_login_logs to surface username, IP, and user agent.
     *
     * @param  int $userId
     * @param  int $limit  Max rows to return (default 50)
     * @return array<int, array<string, mixed>>
     */
    public function getUserHistory(int $userId, int $limit = 50): array
    {
        try {
            $stmt = $this->conn->prepare(
                "SELECT
                     a.id,
                     a.project_code,
                     a.role_name,
                     a.accessed_at,
                     l.username,
                     l.ip_address,
                     l.user_agent
                 FROM  imis_history_access_logs a
                 LEFT JOIN imis_history_login_logs l ON l.id = a.login_log_id
                 WHERE a.user_id = :uid
                 ORDER BY a.accessed_at DESC
                 LIMIT :lim"
            );
            $stmt->bindValue(':uid', $userId, PDO::PARAM_INT);
            $stmt->bindValue(':lim', $limit,  PDO::PARAM_INT);
            $stmt->execute();
            return $stmt->fetchAll(PDO::FETCH_ASSOC);
        } catch (PDOException $e) {
            error_log('SystemAccessLogger::getUserHistory — ' . $e->getMessage());
            return [];
        }
    }

    /**
     * Retrieve the access history for a specific project (newest first).
     * JOINs imis_history_login_logs to surface username, IP, and user agent.
     *
     * @param  int $projectId
     * @param  int $limit
     * @return array<int, array<string, mixed>>
     */
    public function getProjectHistory(int $projectId, int $limit = 100): array
    {
        try {
            $stmt = $this->conn->prepare(
                "SELECT
                     a.id,
                     a.user_id,
                     a.role_name,
                     a.accessed_at,
                     l.username,
                     l.ip_address,
                     l.user_agent
                 FROM  imis_history_access_logs a
                 LEFT JOIN imis_history_login_logs l ON l.id = a.login_log_id
                 WHERE a.project_id = :pid
                 ORDER BY a.accessed_at DESC
                 LIMIT :lim"
            );
            $stmt->bindValue(':pid', $projectId, PDO::PARAM_INT);
            $stmt->bindValue(':lim', $limit,     PDO::PARAM_INT);
            $stmt->execute();
            return $stmt->fetchAll(PDO::FETCH_ASSOC);
        } catch (PDOException $e) {
            error_log('SystemAccessLogger::getProjectHistory — ' . $e->getMessage());
            return [];
        }
    }

    // ─────────────────────────────────────────────────────────────────────────
    // PRIVATE HELPERS
    // ─────────────────────────────────────────────────────────────────────────

    /**
     * Returns true when an access entry for the same user + project exists
     * within the cooldown window.  Uses idx_hal_dedup for a fast index scan.
     */
    private function isWithinCooldown(int $userId, int $projectId): bool
    {
        $threshold = date('Y-m-d H:i:s', strtotime("-{$this->cooldownMinutes} minutes"));

        $stmt = $this->conn->prepare(
            "SELECT 1
               FROM imis_history_access_logs
              WHERE user_id     = :uid
                AND project_id  = :pid
                AND accessed_at >= :threshold
              LIMIT 1"
        );
        $stmt->execute([
            ':uid'       => $userId,
            ':pid'       => $projectId,
            ':threshold' => $threshold,
        ]);

        return (bool) $stmt->fetchColumn();
    }

    /**
     * PHP-generated Asia/Manila timestamp — never relies on MySQL's NOW().
     */
    private function now(): string
    {
        return date('Y-m-d H:i:s');
    }
}
